-- Add missing columns to menu_items table
ALTER TABLE "menu_items" 
ADD COLUMN IF NOT EXISTS "is_vegetarian" BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "is_vegan" BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "is_gluten_free" BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "spice_level" INTEGER,
ADD COLUMN IF NOT EXISTS "preparation_time" INTEGER,
ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS "is_featured" BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "display_order" INTEGER DEFAULT 0; 